### ISSUE TITLE
There is no way to use patron with a SSL server using a self-signed or custom certificate without completely disabling certificate validation

### ISSUE THREAD

**Issue by terabyte** [toland/patron#67]
Using curl itself, you can specify a certificate to use for validation:
```
# create self-signed cert
$ openssl genrsa 4096 > privkey.pem
$ openssl req -new -x509 -key privkey.pem -out cacert.pem -days 10
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:US
State or Province Name (full name) [Some-State]:California
Locality Name (eg, city) []:Palo Alto
Organization Name (eg, company) [Internet Widgits Pty Ltd]:ITOOLS
Organizational Unit Name (eg, section) []:ITOOLS
Common Name (e.g. server FQDN or YOUR name) []:localhost
Email Address []:blah@example.com

# next, start the server
$ openssl s_server -accept 19443 -cert cacert.pem -key privkey.pem
Using default temp DH parameters
Using default temp ECDH parameters
ACCEPT


# In a different terminal
$ curl https://localhost:19443/
curl: (60) SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
# but disabling cert checking works:
curl -k https://localhost:19443/
^C
# s_server is limited, so you have to ctrl-c it, but back in the first terminal you see:
-----BEGIN SSL SESSION PARAMETERS-----
MIGHAgEBAgIDAgQCwBQEIP/oS+No7LAX13bg04ZJCaRFT3BZoSF7eUOxrwHdphKC
BDALqBgZAnpjKvDSkseN5GJStuA0236puXdNJ/QDb5MWcPx6LVkC9iRNCzA6yuc5
24mhBgIEUVyYTaIEAgIBLKQGBAQBAAAApgsECWxvY2FsaG9zdKsDBAEB
-----END SSL SESSION PARAMETERS-----
Shared ciphers:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:SRP-DSS-AES-256-CBC-SHA:SRP-RSA-AES-256-CBC-SHA:DHE-RSA-AES256-SHA:DHE-DSS-AES256-SHA:DHE-RSA-CAMELLIA256-SHA:DHE-DSS-CAMELLIA256-SHA:ECDH-RSA-AES256-SHA:ECDH-ECDSA-AES256-SHA:AES256-SHA:CAMELLIA256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:SRP-DSS-3DES-EDE-CBC-SHA:SRP-RSA-3DES-EDE-CBC-SHA:EDH-RSA-DES-CBC3-SHA:EDH-DSS-DES-CBC3-SHA:ECDH-RSA-DES-CBC3-SHA:ECDH-ECDSA-DES-CBC3-SHA:DES-CBC3-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:SRP-DSS-AES-128-CBC-SHA:SRP-RSA-AES-128-CBC-SHA
CIPHER is ECDHE-RSA-AES256-SHA
Secure Renegotiation IS NOT supported
GET / HTTP/1.1
User-Agent: curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
Host: localhost:19443
Accept: */*

ERROR
shutting down SSL
CONNECTION CLOSED

# But we'd like curl to still check the certificate using our certificate file
# Sure enough, if we do this:
$ curl --cacert cacert.pem https://localhost:19443/
^C
# back in the other window we see:
GET / HTTP/1.1
User-Agent: curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
Host: localhost:19443
Accept: */*

ERROR
shutting down SSL
CONNECTION CLOSED
ACCEPT
# which implies to me that it is working.

```

Here is some ruby equivalent code:
```ruby
#!/usr/bin/env ruby

require 'patron'
require 'awesome_print'

begin

  uri = URI.parse('https://localhost:19443')

  session = Patron::Session.new
  session.timeout = 5
  #session.insecure = true

  response = session.post(uri.to_s, '')
  ap response
end
```
```
# Run this script, get:
$ ./test.rb
/home/cmyers/.rvm/gems/ruby-1.9.2-p320@adms/gems/patron-0.4.18/lib/patron/session.rb:223:in `handle_request': SSL certificate problem, verify that the CA cert is OK. Details: (Patron::Error)
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
# and the server says:
ERROR
139771075016352:error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca:s3_pkt.c:1247:SSL alert number 48
139771075016352:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:s23_lib.c:177:
shutting down SSL
CONNECTION CLOSED

# uncomment the insecure line, and instead see:
$ ./test.rb
/home/cmyers/.rvm/gems/ruby-1.9.2-p320@adms/gems/patron-0.4.18/lib/patron/session.rb:223:in `handle_request': Operation timed out after 5001 milliseconds with 3 bytes received (Patron::TimeoutError)
# and looking at the server, I see:
ACCEPT
POST / HTTP/1.1
Host: localhost:19443
Accept: */*
Content-Length: 0
Content-Type: application/x-www-form-urlencoded

DONE
shutting down SSL
CONNECTION CLOSED

```

In short, what I need is a way to specify a ```session.cacert = 'some_file.pem'``` and get patron to still validate the server certificate using that.

**Comment by julik** [comment]
Closing since it should be fixed now
