### ISSUE TITLE
Patron segfaults under ruby 2.0.0p247 

### ISSUE THREAD

**Issue by bhaberer** [toland/patron#72]
Just a heads up, was doing some checking to see how things were looking for ruby 2.0.0, and Patron was one of the handful of gems that just seems to segfault. 

```
~/src/patron > rvm use 2.0.0
Using /Users/bhaberer/.rvm/gems/ruby-2.0.0-p247

~/src/patron > git fetch upstream

~/src/patron > bundle
The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://rubygems.org' if not.
Fetching gem metadata from http://rubygems.org/.........
Fetching gem metadata from http://rubygems.org/..
Resolving dependencies...
Installing rake (0.9.2.2)
Using bundler (1.3.5)
Installing diff-lcs (1.1.3)
Using patron (0.4.18) from source at .
Installing rake-compiler (0.7.9)
Installing rcov (0.9.11)
Installing rspec-core (2.7.1)
Installing rspec-expectations (2.7.0)
Installing rspec-mocks (2.7.0)
Installing rspec (2.7.0)
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.

~/src/patron > bundle exec irb
The source :rubygems is deprecated because HTTP requests are insecure.
Please change your source to 'https://rubygems.org' if possible, or 'http://rubygems.org' if not.
2.0.0-p247 :001 > require 'patron'
 => true
2.0.0-p247 :002 > session = Patron::Session.new
 => #<Patron::Session:0x007fca24110648 @headers={}, @timeout=5, @connect_timeout=1, @max_redirects=5, @auth_type=:basic>
2.0.0-p247 :003 > session.base_url = 'http://localhost/'
 => "http://localhost/"
2.0.0-p247 :004 > session.get ''
/Users/bhaberer/src/patron/lib/patron/session.rb:228: [BUG] Segmentation fault
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-darwin12.4.0]

- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/CrashReporter
     * /Library/Logs/CrashReporter
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   the more detail of.

-- Control frame information -----------------------------------------------
c:0021 p:---- s:0092 e:000091 CFUNC  :handle_request
c:0020 p:0478 s:0088 e:000087 METHOD /Users/bhaberer/src/patron/lib/patron/session.rb:228
c:0019 p:0017 s:0077 e:000076 METHOD /Users/bhaberer/src/patron/lib/patron/session.rb:129
c:0018 p:0008 s:0072 e:000071 EVAL   (irb):4 [FINISH]
c:0017 p:---- s:0070 e:000069 CFUNC  :eval
c:0016 p:0024 s:0063 e:000062 METHOD /Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb/workspace.rb:86
c:0015 p:0025 s:0056 e:000054 METHOD /Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb/context.rb:380
c:0014 p:0022 s:0050 e:000049 BLOCK  /Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb.rb:492
c:0013 p:0040 s:0042 e:000041 METHOD /Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb.rb:624
c:0012 p:0009 s:0037 e:000036 BLOCK  /Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb.rb:489
c:0011 p:0118 s:0033 e:000032 BLOCK  /Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb/ruby-lex.rb:247 [FINISH]
c:0010 p:---- s:0030 e:000029 CFUNC  :loop
c:0009 p:0007 s:0027 e:000026 BLOCK  /Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb/ruby-lex.rb:233 [FINISH]
c:0008 p:---- s:0025 e:000024 CFUNC  :catch
c:0007 p:0015 s:0021 e:000020 METHOD /Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb/ruby-lex.rb:232
c:0006 p:0030 s:0018 E:000298 METHOD /Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb.rb:488
c:0005 p:0008 s:0015 e:000014 BLOCK  /Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb.rb:397 [FINISH]
c:0004 p:---- s:0013 e:000012 CFUNC  :catch
c:0003 p:0143 s:0009 E:000578 METHOD /Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb.rb:396
c:0002 p:0122 s:0004 E:0019c8 EVAL   /Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/bin/irb:16 [FINISH]
c:0001 p:0000 s:0002 E:000698 TOP    [FINISH]

/Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/bin/irb:16:in `<main>'
/Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb.rb:396:in `start'
/Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb.rb:396:in `catch'
/Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb.rb:397:in `block in start'
/Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb.rb:488:in `eval_input'
/Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb/ruby-lex.rb:232:in `each_top_level_statement'
/Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb/ruby-lex.rb:232:in `catch'
/Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb/ruby-lex.rb:233:in `block in each_top_level_statement'
/Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb/ruby-lex.rb:233:in `loop'
/Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb/ruby-lex.rb:247:in `block (2 levels) in each_top_level_statement'
/Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb.rb:489:in `block in eval_input'
/Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb.rb:624:in `signal_status'
/Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb.rb:492:in `block (2 levels) in eval_input'
/Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb/context.rb:380:in `evaluate'
/Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb/workspace.rb:86:in `evaluate'
/Users/bhaberer/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/irb/workspace.rb:86:in `eval'
(irb):4:in `irb_binding'
/Users/bhaberer/src/patron/lib/patron/session.rb:129:in `get'
/Users/bhaberer/src/patron/lib/patron/session.rb:228:in `request'
/Users/bhaberer/src/patron/lib/patron/session.rb:228:in `handle_request'

-- C level backtrace information -------------------------------------------

-- Other runtime information -----------------------------------------------
```

**Comment by mattpickle** [comment]
We switched from patron to typhoeus.  No more segfaults.

**Comment by marshall-lee** [comment]
Guys, could you please try to reproduce your segfaults with #93? I fixed some segfaults but not sure if there are any more such issues in C code.

**Comment by hggh** [comment]
@marshall-lee  I have tested the commit from #93 the patch resolves the issue with the Segfault. But the tests fail within ruby 2.2 on debian.

**Comment by hggh** [comment]
update: with #92 it works within ruby2.2. @toland could you please release a new gem?

**Comment by marshall-lee** [comment]
yeah, would be good

**Comment by toland** [comment]
Hey guys. Sorry it took me so long to respond to this. I was out of town for a week and it took me a while to get my dev environment set back up once I returned. Anyway, I have released version 0.5.0 of Patron with all of the fixes to date.

All of the tests pass for me with Ruby 2.2.3 on OSX. Let me know if you see any other issues.

**Comment by julik** [comment]
@desmondhume As a matter of fact I know exactly what this is. And it only happens on OSX. The problem is we can't fix it within Patron itself. If you are still experiencing the issue, you need to install curl from homebrew and force it to `--with-openssl`. The reason this stopped happening is because under Passenger you do your `curl_easy_perform` in a forked process, which triggers a bug in Apple's secure transport.

**Comment by julik** [comment]
@pravi so far there was a couple of segfaults fixed AFAIK, and one segfault is a known issue with OSX curl linked against Apple SSL libraries, and only when using forking. Moreover, this specific segfault also happens in curb and in various PHP forking situations too. It is very unlikely it is relevant for debian.

I was not able to find references to build logs for debian bug you likned. Meanwhile, you opened issues on 3 projects to remove Patron support (???), while the actual cause of the issue was not found until recently. Maybe you could let them know we are still kicking now?

**Comment by pravi** [comment]
@julik I have closed those issues linking to your response.

**Comment by julik** [comment]
Thanks!
